worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;

    # Список серверов, куда будут проксироваться запросы.
    upstream aspnet-app {
        # Метод балансировки нагрузки по умолчанию (round-robin)
        server app1:5001;
        server app2:5002;

        # Метод балансировки нагрузки least_conn (наименьшее количество соединений)
        # least_conn;

        # Метод балансировки нагрузки ip_hash (постоянное соединение с одного IP)
        # ip_hash;
    }

    # 8080 порт - точка входа для пользователей
    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://aspnet-app;
        }
    }
}