worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;

    # Список серверов, куда будут проксироваться запросы.
    upstream aspnet-app {
        # Метод балансировки нагрузки по умолчанию (round-robin)
        server app1:5001;
        server app2:5002;

        # Метод балансировки нагрузки least_conn (наименьшее количество соединений)
        # least_conn;

        # Метод балансировки нагрузки ip_hash (постоянное соединение с одного IP)
        # ip_hash;
    }

    upstream rank_calculator-app {
        # Метод балансировки нагрузки по умолчанию (round-robin)
        server rank_calculator1:5003;
        server rank_calculator2:5004;
    }

    # 8080 порт - точка входа для пользователей
    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://aspnet-app;
        }
    }

     server {
        listen 80;

        # Настроим, чтобы обработать запросы на /rankHub
        location /rankHub {
            proxy_pass http://rank_calculator-app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Text-Id $http_x_text_id;
        }

        # Другие настройки сервера могут быть здесь (например, для статических файлов)
        location / {
            root /var/www/html;
            index index.html index.htm;
        }
    }
}